// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrunSatis.Models;

#nullable disable

namespace UrunSatis.Migrations
{
    [DbContext(typeof(UrunSatisContext))]
    partial class UrunSatisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Turkish_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrunSatis.Models.Kullanici", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("aktif_mi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<string>("Isim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("isim");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kullanici_adi");

                    b.Property<int>("KullaniciTipi")
                        .HasColumnType("int")
                        .HasColumnName("kullanici_tipi");

                    b.Property<byte[]>("OlusturulmaTarihi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturulma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sifre");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("silinme_tarihi");

                    b.Property<DateTime?>("SonAktifTarih")
                        .HasColumnType("datetime")
                        .HasColumnName("son_aktif_tarih");

                    b.Property<string>("Soyisim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("soyisim");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "KullaniciAdi" }, "kullanici_adi")
                        .IsUnique();

                    b.ToTable("kullanici", (string)null);
                });

            modelBuilder.Entity("UrunSatis.Models.Urun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("aktif_mi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<long>("Fiyat")
                        .HasColumnType("bigint")
                        .HasColumnName("fiyat");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kategori");

                    b.Property<byte[]>("OlusturulmaTarihi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturulma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("resim_yolu");

                    b.Property<int>("StokMiktar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("urun", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
